# Google Gemini Configuration (FREE TIER)
server.port=8081

# Google Gemini Configuration (NO LIMITS)
gemini.api.key=  "API KEY HERE"
spring.application.name=chatbot-backend
logging.level.com.example.chatbot=INFO
